config/routes.rb
LawyerdApp::Application.routes.draw do

  root 'welcome#index'

  resources :users
  resources :partners
  resources :clients
  resources :assignment_types
  resources :assignments
  resources :notes
  get  "/session/new"  => "session#new"
  post "/session"      => "session#create"
  get  "/logout"       => "session#destroy"

  get '/users/:id/:sort_by' => 'users#show', as: 'sort_by'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :client
  has_one :partner, :through => :client
  has_one :user, :through => :partner

  belongs_to :assignment_type

  has_many :notes

end

app/models/assignment_type.rb
class AssignmentType < ActiveRecord::Base
  belongs_to :user
  has_many :assignments
end

app/models/client.rb
class Client < ActiveRecord::Base

  belongs_to :partner
  has_many :assignments

  validates(:name,     { :presence     => true })

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :assignment
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  belongs_to :user
  has_many :clients
  has_many :assignments, :through => :clients

  validates(:name,     { :presence     => true })

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :partners
  has_many :clients, :through => :partners
  has_many :assignments, :through => :clients
  has_many :notes, :through => :assignments

  has_many :assignment_types

  validates(:email,     { :presence     => true })
  validates(:email,    { :uniqueness   => { case_sensitive: false }})

  validates(:name,     { :presence     => true })

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  helper_method(:current_user, :logged_in?)

  def require_admin
    if logged_in? && current_user.admin
      return true
    else
      flash[:error] = "ADMIN ONLY"
      redirect_to root_path
    end
  end

end

app/controllers/assignment_types_controller.rb
class AssignmentTypesController < ApplicationController

  def create
    @assignment_type = AssignmentType.new(assignment_type_params)
    @assignment_type.user = current_user
    if @assignment_type.save
      flash[:notice] = "AssignmentType #{@assignment_type.name} added"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Invalid AssignmentType Properties"
      redirect_to user_path(current_user)
    end
  end

  private

  def assignment_type_params
    params.require(:assignment_type).permit(
      :name
    )
  end

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  def create
    @assignment = Assignment.new(assignment_params)

    if @assignment.save
      flash[:notice] = "Assignment added"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Invalid Assignment Properties"
      redirect_to user_path(current_user)
    end
  end

  def edit
    @assignment = Assignment.find(params[:id])
    @clients = current_user.clients
    @types = current_user.assignment_types
  end

  def update
    @assignment = Assignment.find(params[:id])

    if @assignment.update(assignment_params)
      flash[:notice] = "Assignment updated"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Invalid Assignment Properties"
      render :edit
    end
  end

  def destroy
    assignment = Assignment.find_by(id: params[:id])
    if assignment.destroy
      flash[:notice] = "Assignment removed"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Couldn't Remove Assignment"
      redirect_to user_path(current_user)
    end
  end

  def show
    @assignment = Assignment.find(params[:id])
    @note = Note.new
  end

  private

  def assignment_params
    params.require(:assignment).permit(
      :assigned_date,
      :due_date,
      :client_id,
      :assignment_type_id
    )
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:notice] = "Client #{@client.name} added"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Invalid Client Properties"
      redirect_to user_path(current_user)
    end
  end

  private

  def client_params
    params.require(:client).permit(
      :name,
      :partner_id
    )
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    @note = Note.new(note_params)
    assignment = Assignment.find(@note.assignment_id)
    if @note.save
      flash[:notice] = "Note added"
      redirect_to assignment_path(assignment)
    else
      flash[:notice] = "Invalid Note Properties"
      redirect_to assignment_path(assignment)
    end
  end

  def destroy
    note = Note.find_by(id: params[:id])
    assignment = Assignment.find(note.assignment_id)
    if note.destroy
      flash[:notice] = "Note removed"
      redirect_to assignment_path(assignment)
    else
      flash[:notice] = "Couldn't Remove Note"
      redirect_to assignment_path(assignment)
    end
  end

  private

  def note_params
    params.require(:note).permit(
      :content,
      :assignment_id
    )
  end

end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController

  def create
    @partner = Partner.new(partner_params)
    @partner.user = current_user
    if @partner.save
      flash[:notice] = "Partner #{@partner.name} added"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Invalid Partner Properties"
      redirect_to user_path(current_user)
    end
  end

  private

  def partner_params
    params.require(:partner).permit(
      :name
    )
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in Successfully!"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Invalid Credentials"
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged Out Successfully!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Thanks for signing up!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash_message = ""
      @user.errors.messages.each do |field, message|
        flash_message += ": " + field.to_s.titleize + " " + message.first + " :"
      end
      flash[:notice] = flash_message
      redirect_to root_path
    end
  end

  def show
    @user = User.find(current_user.id) #not used
    sort_by = params[:sort_by] || 'id'
    @assignments = current_user.assignments.order(sort_by)
    @partners = current_user.partners
    @partner = Partner.new
    @clients = current_user.clients
    @client = Client.new
    @types = current_user.assignment_types
    @type = AssignmentType.new
    @assignment = Assignment.new
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @user = User.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/assignment_types/_form.html.erb
<%= form_for(@type) do |f| %>
  <%= f.text_field :name, :placeholder => 'Enter Type' %><br>
  <%= f.submit %>
<% end %>

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <%= f.label(:client) %>
  <%= f.collection_select(:client_id, @clients, :id, :name) %>
  <%= f.label(:assignment_type) %>
  <%= f.collection_select(:assignment_type_id, @types, :id, :name) %>
  <%= f.date_field :assigned_date, :placeholder => 'mm/dd/yyyy' %>
  <%= f.date_field :due_date, :placeholder => 'mm/dd/yyyy' %>
  <%= f.submit %>
<% end %>

app/views/assignments/edit.html.erb
<div align="center">
  <br>
  <br>
  <%= render 'form' %>
  <br>
  <br>
<div>

app/views/assignments/show.html.erb
<div align="center">
<br>
<br>
<% @assignment.notes.each do |note| %>
  <%= note.content %><br><span style="font-size: x-small;"><%= link_to 'delete', note_path(note), :method => :delete, :confirm => "Are you sure?" %></span><br><br>
<% end %>


<%= render 'notes/form' %>

</div>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <%= f.label(:partner) %>
  <%= f.collection_select(:partner_id, @partners, :id, :name) %>
  <%= f.text_field :name, :placeholder => 'Enter Client Name' %>
  <%= f.submit %>
<% end %>

app/views/layouts/_login.html.erb
<div class="login">

<% if logged_in? %>
  <a href="/users/<%= current_user.id %>">
  <%= current_user.name %></a><br>
  <span style="font-size: x-small"><a href="/logout"> Logout</a></span>
<% else %>
  <%= form_tag("/session", method: "post") do %>
    <%= text_field_tag(:email, nil, placeholder: 'Email') %> <%= password_field_tag(:password, nil, placeholder: 'Password') %> <%= submit_tag("Login") %>
  <% end %>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>lawyerD</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div class="container">
      <span id="logo">
        <% if logged_in? %>
          <%= link_to 'lawyerD', user_path(current_user) %>
        <% else %>
          <%= link_to 'lawyerD', root_path %>
        <% end %>

      </span><%= render 'layouts/login' %>
    </div>
  </header>

  <div class="container">

    <% flash.each do |key, value| %>
        <div class="flash"><%= value %></div>
    <% end %>

    <%= yield %>

    <footer>
    </footer>
  </div>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <%= f.hidden_field :assignment_id, :value => @assignment.id %>
  <%= f.text_field :content, :placeholder => 'Enter Note' %><br>
  <%= f.submit %>
<% end %>

app/views/partners/_form.html.erb
<%= form_for(@partner) do |f| %>
  <%= f.text_field :name, :placeholder => 'Enter Partner Name' %><br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div align="center">
<p>Hi <%= current_user.name %></p>
<p>Today is <%= Time.now.to_date.to_formatted_s(:long) %></p>
<h4>Your Assignments</h4><br>
<table width="800px" class="assignmentsTable">
  <thead>
    <th><strong><%= link_to 'Client', "/users/#{current_user.id}/client_id" %></strong></th>
    <th><strong><%= link_to 'Type', "/users/#{current_user.id}/assignment_type_id" %></strong></th>
    <th><strong><%= link_to 'Partner', "/users/#{current_user.id}/partner_id" %></strong></th>
    <th><strong><%= link_to 'Assigned Date', "/users/#{current_user.id}/assigned_date" %></strong></th>
    <th><strong><%= link_to 'Due Date', "/users/#{current_user.id}/due_date" %></strong></th>
    <th><strong><%= link_to 'Days Left', "/users/#{current_user.id}/due_date" %></strong></th>
    <th><strong>Notes</strong></th>
    <th><strong> </strong></th>
    <th><strong> </strong></th>
  </thead>
  <tbody>
    <% @assignments.each do |a| %>
      <%# binding.pry %>
      <% if (a.due_date - Time.now.to_date).to_i < 7 %>
      <tr class="green" >
      <% elsif (a.due_date - Time.now.to_date).to_i > 7 && (a.due_date - Time.now.to_date).to_i < 15 %>
      <tr class="yellow" >
      <% else %>
      <tr>
      <% end %>
        <td><%= a.client.name %></td>
        <td><%= a.assignment_type.name %></td>
        <td><%= a.partner.name %></td>
        <td><%= a.assigned_date.to_formatted_s(:long) %></td>
        <td><%= a.due_date.to_formatted_s(:long) %></td>
        <td><%= (a.due_date - Time.now.to_date).to_i %></td>
        <td><%= link_to a.notes.length, assignment_path(a) %></td>
        <td><span style="font-size: small;"><%= link_to 'Edit', edit_assignment_path(a) %></span></td>
        <td><span style="font-size: small;"><%= link_to "Delete", assignment_path(a), :method => :delete, :confirm => "Are you sure?" %></span></td>
      </tr>
    <% end %>
  </tbody>
</table><br>
<%= render 'assignments/form' %>
<br><br>
<h4>Your Partners</h4><br>
<% @partners.each do |p| %>
  <%= p.name %> - <%= p.clients.size %> clients - <%= p.assignments.length %> assignments<br>
<% end %><br>
<%= render 'partners/form' %>
<br><br>
<h4>Your Clients</h4><br>
<% @clients.each do |c| %>
  <%= c.name %> - <%= c.assignments.length %> assignments<br>
<% end %><br>
<%= render 'clients/form' %>
<br><br>
<h4>Your Assignment Types</h4><br>
<% @types.each do |t| %>
  <%= t.name %> - <%= t.assignments.length %> assignments<br>
<% end %><br>
<%= render 'assignment_types/form' %>
</div>

app/views/welcome/index.html.erb
<div class="signup">
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <%# f.label(:email) %>
  <%= f.text_field :email, placeholder: 'Your Email' %><br><br>
  <%# f.label(:name) %>
  <%= f.text_field :name, placeholder: 'First Name' %><br><br>
  <%# f.label(:password) %>
  <%= f.password_field :password, placeholder: 'New Password' %><br><br>
  <%# f.label(:password_confirmation) %>
  <%= f.password_field :password_confirmation, placeholder: 'Re-enter Password' %><br><br>
  <%= f.submit 'Sign Up', :class => 'signupbutton'%>
<% end %>
</div>
<div class="welcome">
<br>
Welcome to lawyerD<br><br>
<p>Where you can manage your</p><p>assignments</p><p>partners</p><p>due dates</p><p>etc.</p>
</div>